[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "onestepx-bench"
version = "0.1.0"
description = "Benchmark harness for OneStepX Terminal kernel"
authors = [{name="Collapse Logic Labs"}]
dependencies = []
