name: Upload Python Package
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Upgrade build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build twine
      - name: Clean and build
        run: |
          rm -rf dist build *.egg-info src/*.egg-info
          python -m build
      - name: Sanity check distributions
        run: |
          python -m twine check dist/*
          python - << 'PY'
import glob, zipfile
whl = sorted(glob.glob("dist/*.whl"))[-1]
with zipfile.ZipFile(whl) as z:
    meta = [n for n in z.namelist() if n.endswith("dist-info/METADATA")][0]
    print("=== METADATA HEAD ===")
    print("\n".join(z.read(meta).decode().splitlines()[:15]))
PY
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
