name: Upload Python Package
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build and check
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build twine
          rm -rf dist build *.egg-info src/*.egg-info
          python -m build
          python -m twine check dist/*
          python - <<'PY'
import glob, zipfile
whls = sorted(glob.glob("dist/*.whl"))
assert whls, "no wheels built"
whl = whls[-1]
with zipfile.ZipFile(whl) as z:
    meta = [n for n in z.namelist() if n.endswith("dist-info/METADATA")][0]
    print("=== METADATA HEAD ===")
    print("\n".join(z.read(meta).decode().splitlines()[:15]))
PY

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/
