name: Upload Python Package
on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build and check
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build twine
          rm -rf dist build *.egg-info src/*.egg-info
          python -m build
          python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/
